### PR TITLE
I feel Stockfish multi-variant from https://github.com/ddugovic/Stockfish is better than Stockfish 13

### PR DESCRIPTION
**Pull request by oivas000**

### CODE REVIEW

**Comment by oivas000** [comment]
Sorry 
I have a Bot on https://Lichess.org
When I used Stockfish13 with nnue for my bot it defeated by a varriant bot that using sf multi-varriant engine with nnue.
I understand that SF multi-varriant is better that SF13
No need to test varriant. It can play standard.
My branch is same to Ddugovic
This test not made for varriant.
This is my first test. I put minimum number of game
I have a desire to become a Stockfish developer.
If you didn't like it reject it.
Thanks

**Comment by oivas000** [comment]
No need to direct this test to varriant fishnet
I made this to play with sf13

**Comment by TheYoBots** [comment]
These are the tests between Multi Variant Stockfish and Stockfish has already been done.

ELO: 28.55 +-9.1 (95%) LOS: 100.0%  
Total: 2000 W: 440 L: 276 D: 1284
http://35.161.250.236:6543/tests/view/589518b66e23db014ac09f6b

Though this is an old test, Stockfish seems to have an extremely large and clear dominance against Multi Variant Stockfish. So I don’t see why you think Stockfish would be weaker. If it is just based on the lichess bot, then there are other factors that affect playing strength such a cpu cores, or engine options or even connection to lichess.

**Comment by oivas000** [comment]
Yes, My opinion is based on Lichess bot

**Pull request closed without merging**
