### PR TITLE
Fullfail-lmr2

### PR DESCRIPTION
**Pull request by OfekShochat**
passed both ltc and stc:
stc:
https://tests.stockfishchess.org/tests/view/620cf0ec57b7b652f23958a1
LLR: 2.94 (-2.94,2.94) <0.00,2.50>
Total: 67408 W: 17808 L: 17483 D: 32117
Ptnml(0-2): 264, 7188, 18457, 7549, 246 
ltc:
https://tests.stockfishchess.org/tests/view/620d161357b7b652f2395c9e
LLR: 2.94 (-2.94,2.94) <0.50,3.00>
Total: 65168 W: 17344 L: 17009 D: 30815
Ptnml(0-2): 36, 6423, 19337, 6746, 42

### CODE REVIEW

**Comment by Snowden83** [comment]
_Unfortunately, the Stockfish organization has corrupted to the point that owners repositories **pay money to GitHub to delete posts of people who disagree with them**, no matter how well true. I'll demonstrate a few incidents to prove this._

recently my friend created a topic here titled "**Admins of the Stockfish repositories tyrannically deny freedom of expression**". https://github.com/mcostalba/Stockfish/pull/321

image

It had nearly 10k views and 100 posts , I explained in this topic that This patch (from 5 nov 2022 Author: @vondele ) needs to be cancelled. https://github.com/official-stockfish/Stockfish/commit/ad2aa8c06f438de8b8bb7b7c8726430e3f2a5685 Due to this patch, the value can jump very sharply in one or a couple of moves that it cause wrong calculated. 

**Example: 8/7Q/3p1K2/1p4P1/8/8/1k6/3q4 w - - 2 53**

sf

But they deleted my friend's posts from GitHub , Also her account is inaccessible (@komodochess)

image

@protonspring @ddugovic @atumanian @chesserik @pschneider1968 @OfekShochat @Vizvezdenec @Disservin @joergoster @silversolver1 @Sopel97 @ppigazzini @lucasart @FauziAkram @BM123499 @MichaelB7 @XinTheDark  @noobpwnftw @liallis

Please explain who delete all posts , why ? This proves that also GitHub staff member deny freedom of expression !

**Comment by Vizvezdenec** [comment]
Пошёл
Нахуй
Уёбок

**Comment by protonspring** [comment]
Please do not feed the trolls.

**Comment by Lovely-Chess** [comment]
I confirm this pull , Vondele merged his pull without paying attention to my words 

- https://github.com/official-stockfish/Stockfish/pull/4373

@protonspring You can use `multipv` to find out how wrong this pull is ....

```
Stockfish 15.1 by the Stockfish developers (see AUTHORS file)
position fen 8/7Q/3p1K2/1p4P1/8/8/1k6/3q4 w - - 2 53
setoption name multipv value 2
go depth 30
info string NNUE evaluation using nn-ad9b42354671.nnue enabled
info depth 1 seldepth 1 multipv 1 score cp 247 nodes 62 nps 20666 hashfull 0 tbhits 0 time 3 pv h7h2 d1c2 h2c2 b2c2
info depth 1 seldepth 1 multipv 2 score cp 16 nodes 62 nps 20666 hashfull 0 tbhits 0 time 3 pv h7e4
info depth 2 seldepth 2 multipv 1 score cp 247 nodes 158 nps 39500 hashfull 0 tbhits 0 time 4 pv h7h2 d1c2 h2c2 b2c2
info depth 2 seldepth 2 multipv 2 score cp 16 nodes 158 nps 39500 hashfull 0 tbhits 0 time 4 pv h7e4
info depth 3 seldepth 3 multipv 1 score cp 16 nodes 359 nps 89750 hashfull 0 tbhits 0 time 4 pv h7e4
info depth 3 seldepth 3 multipv 2 score cp -12 nodes 359 nps 89750 hashfull 0 tbhits 0 time 4 pv g5g6 d1f3 f6g5
info depth 4 seldepth 2 multipv 1 score cp 16 nodes 470 nps 117500 hashfull 0 tbhits 0 time 4 pv h7e4
info depth 4 seldepth 4 multipv 2 score cp -1 nodes 470 nps 117500 hashfull 0 tbhits 0 time 4 pv g5g6 d1f3 f6g7
info depth 5 seldepth 2 multipv 1 score cp 756 nodes 617 nps 154250 hashfull 0 tbhits 0 time 4 pv h7e4
info depth 5 seldepth 5 multipv 2 score cp 27 nodes 617 nps 154250 hashfull 0 tbhits 0 time 4 pv g5g6 d1d4 f6f7

.....

info depth 30 seldepth 53 multipv 1 score cp 95 nodes 21990363 nps 1328722 hashfull 1000 tbhits 0 time 16550 pv h7e4 d1f1 f6e7 f1c4 e4g2 b2a3 g2f3 a3a4 g5g6 c4c7 e7f6 c7d8 f6f5 d8f8 f5g4 f8e8 f3d1 a4a3 d1a1 a3b4 a1f6 e8e2 g4g3 e2e3 g3h4 e3e1 h4g5 e1g1 g5f5 g1c5 f5e6 c5c8 e6f7 c8d7 f6e7 d7f5 f7g7 b4a3 e7e3 a3a2 e3e2 a2a1
info depth 30 seldepth 48 multipv 2 score cp 65 nodes 21990363 nps 1328722 hashfull 1000 tbhits 0 time 16550 pv h7h2 b2a1 h2f4 b5b4 f4b4 d1f3 f6g7 f3e3 b4a5 a1b2 a5b5 b2c3 b5f5 e3e7 g7h6 e7e3 f5d5 c3b2 h6h5 e3e2 h5h4 e2e1 h4g4 e1g1 g4f5 g1f2 f5e6 f2e3 e6f7 e3f4 f7g8 f4g3 d5d4 b2b3 d4d1 b3a2 d1c2 a2a1 g5g6
bestmove h7e4 ponder d1f1
```

@atumanian  Could you please write your opinion here ? I think another pull is merged in spite of your warning

**Comment by Lovely-Chess** [comment]
@ddugovic @Craftyawesome @pschneider1968 

- I sent the position `8/7Q/3p1K2/1p4P1/8/8/1k6/3q4 w - - 2 53` on https://github.com/official-stockfish/Stockfish/pull/4373
but they deleted it 

image

**This proves that Vondele want to merge his wrong pulls forever and never he admits his mistakes** 

Previously, @ddobbelaere was against the merging of this pull

> I personally like @vdbergh his suggestion (PR #4218) more than this PR (I changed my mind...). It is conceptually simpler and provides a non-linear relation between the internal value and the reported UCI score in centipawns. With this PR, the relation is by definition linear. The fact that it relates to the earlier referenced paper (and has an easy rule of thumb: "1cp means 1 elo handicap") is also a plus IMHO.
> 
> This way, more focus is being put onto the WDL model (and it's derived cp value, now strictly defined) and less on some internal value.
> 
> _Originally posted by @ddobbelaere in https://github.com/official-stockfish/Stockfish/issues/4216#issuecomment-1301941076_

**Comment by OfekShochat** [comment]
What did I do for this to happen lol

**Comment by mhouppin** [comment]
> * I sent the position `8/7Q/3p1K2/1p4P1/8/8/1k6/3q4 w - - 2 53` on [Update WLD model official-stockfish/Stockfish#4373](https://github.com/official-stockfish/Stockfish/pull/4373)
>   but they deleted it
>
FWIW, I ran a small search at depth 27 (with 256 MB hash if anyone cares enough to reproduce my results) with the commit that updated the normalization and the commit prior to it. +0.69 for the former, +0.75 for the latter. Claiming that SF used to evaluate the position higher before normalization is irrelevant to the actual objective pursued by normalizing reported evals. Furthermore, the position you posted is not the one that features the +3.26 evals from your first comment on the PR.

> Previously, @ddobbelaere was against the merging of this pull
>
No. He said he preferred another PR with a different model for eval normalization that involved the current WDL model combined with a logit function, while acknowledging that this other model might confuse SF users due to the non-linearity in the produced evals. The point of these two PRs has always been to normalize SF's evals to facilitate their interpretation.

Once again, please stop pinging me randomly on other people's repositories.

**Comment by atumanian** [comment]
@Snowden83
Sorry, I don't know who deleted the topic.
By the way, I had created a topic on the [Fishcooking forum](https://groups.google.com/g/fishcooking/c/e05Imm5ivqE). We can discuss there the problem of admins repressing other opinions.

**Comment by DragonbyKomodo** [comment]
@atumanian Thanks for support ,[Fishcooking](https://groups.google.com/g/fishcooking/c/e05Imm5ivqE) where privacy and freedom come first
I know someone who work in GitHub and repressing other opinions.

@mhouppin , My friend answered your question completely But they deleted all her posts and her account is inaccessible...
I am just attaching the first position you wanted **Please note that in this position, only SF calculates the score incorrectly**
- This is related to https://github.com/official-stockfish/Stockfish/pull/4216

image

**In second position , SF calculates both (bestmove , score) incorrectly !!!**

- This is related to https://github.com/official-stockfish/Stockfish/pull/4373

image

Good Luck

**Comment by atumanian** [comment]
@DragonbyKomodo 
I'm pleased to help you. Since it's Marco's own repository, only he himself or the GitHub staff could've deleted the PR.

Regarding your positions, take into account the fact that the two commits you are referring to only multiply every displayed score by a constant. They are "no functional change" and don't change the move selection algorithm at all and don't change the internal score of positions.

**Comment by DragonbyKomodo** [comment]
```diff
-     constexpr double as[] = {  -0.58270499,    2.68512549,   15.24638015,  344.49745382};
-     constexpr double bs[] = {  -2.65734562,   15.96509799,  -20.69040836,   73.61029937 };
+     constexpr double as[] = {   0.33677609,   -4.30175627,   33.08810557,  365.60223431};
+     constexpr double bs[] = {  -2.50471102,   14.23235405,  -14.33066859,   71.42705250 };
```

@atumanian changing WLD model variables is Infinitesimal functional change. **This is not equal to  "no functional change"**

_After many commits in many years , This cause functional change_

**Comment by atumanian** [comment]
@DragonbyKomodo
The `as` and `bs` arrays are defined inside the `win_rate_model` function. Look through the code where this function is called. It isn't used during normal engine operations.

**Comment by DragonbyKomodo** [comment]
> It is linear. Before normalization `internal units / 208` is value in pawns. Now instead it divides by NormalizeToPawnValue (initially 348, shortly after 361, and now 394)
>
> _Originally posted by @Craftyawesome in https://github.com/official-stockfish/Stockfish/issues/4373#issuecomment-1415315521_

@atumanian If you divide 394 / 208 ≃ 2 , for example if previous score was 4.0 , now score is 2.0 ...

 **This can't alone changes functional changes , But it causes changes when the Neural Network is trained based on these values**
 
image

image

image

I want from @vdbergh to explain this for you

**Comment by MinetaS** [comment]
Let me move my words on Discord to here:

> This is the attitude from people who claim freedom of speech:
> - Impersonating developers of SF or other engines
> - Creating dozens of Github accounts (not to mention which obviously violates Github ToS)

**Comment by atumanian** [comment]
@DragonbyKomodo 
 > If you divide 394 / 208 ≃ 2 , for example if previous score was 4.0 , now score is 2.0 ...
 
You can do the following test. Select two versions: one with the "Update WDL model" patch and another without it (but it's important that otherwise the versions be the same; there must be no other differences between the versions). Then do the "bench" test or test any position you like. The depth, hash size and must be the same between the two versions and there must be one thread. Also clear the hash before searching positions.
The expected version is that all scores change proportionally, except the extreme range (mate scores, tb wins, known wins). If it's the case, you should blame different parts of code for the abrupt change of the score. If not, the "Update WDL model" patch is indeed problematic.

**Comment by atumanian** [comment]
@MinetaS 

> Let me move my words on Discord to here:
> 
> > This is the attitude from people who claim freedom of speech:
> > 
> > * Impersonating developers of SF or other engines
> > * Creating dozens of Github accounts (not to mention which obviously violates Github ToS)

I haven't impersonated any developer and you won't find dozens of GitHub accounts by me. Why did Vondele blocked me and doesn't allow others to express an opinion he doesn't like? Is this behaviour acceptable?

**Comment by ddugovic** [comment]
Question: on your hardware, can you verify your revert of the patch is a strength improvement?

Assuming you don't have the same grade of hardware that the SF test cluster uses (so you can't afford thousands of test gamse) you could try to invent a new test methodology.  Here are tools I've used in the past:

https://www.chessprogramming.org/Test-Positions
https://www.arasanchess.org/testsuite.shtml
https://www.chessprogramming.org/Bratko-Kopec_Test#External_Links

I have no opinion and no further information to share, sorry.

**Comment by snicolet** [comment]
Please stop pinging me.

**Comment by ghost** [comment]
Hi @ddugovic , I wanted to answer your question but @GitHub suspended my account ....

> Question: on your hardware, can you verify your revert of the patch is a strength improvement?

This is not one commit to verify revert of the patch ,  Too many commits in the several years

As I mentioned earlier , This pulls are Infinitesimals functional changes but @vondele thinks no functional changes
image

Screenshot Sitting on Top of the World

The method of constructing infinitesimals of the kind used in nonstandard analysis depends on the WLD model and which collection of axioms are used. We consider here systems where infinitesimals can be shown to exist. 

image

Screenshot Sitting on Top of the World2

@vdbergh @ppigazzini @Vizvezdenec @Disservin @peregrineshahin @RogerThiede @PGG106 @mhouppin @XInTheDark @dav1312 @Karma-Tron  @bftjoe @jamesbraza @PedanticHacker @GH0ST-Unavailabe

**Comment by bftjoe** [comment]
> Please stop pinging me.

I highly recommend blocking atumanian on his main account. He will make alt accounts to ping you, but they will be banned as soon as you report it to github. I hope they ban his main account soon.

**Comment by atumanian** [comment]
@ghost
Sorry, I don't understand how these formulas are related to the PRs in question.

@bftjoe
What my main account are you referring to?

**Comment by LichessMaster** [comment]
@atumanian Please stop trolling . You will get yourself banned.

**Comment by lucametehau** [comment]
Github should implement an IP ban just for this guy...
Btw, if you haven't realised this by now, you aren't helping anyone, nor you are doing any justice. Opening pointless PRs/Issues doesn't help SF community by any means. And lately you seem to create a lot of fake accounts just to randomly ping people and just be annoying in general.

P.S.: If you really want to help SF community, you could start by understanding how SF works. Then, maybe, you could even answer some of the "Issues" you opened. And pls don't ping again =)

**Comment by bftjoe** [comment]
> @ghost
> Sorry, I don't understand how these formulas are related to the PRs in question.
> 
> @bftjoe
> What my main account are you referring to?

Do you think pretending those other accounts aren't yours does anything? Why do you think github keeps banning your alt accounts? Do you really think pretending to talk to yourself fools anyone?

**Comment by PedanticHacker** [comment]
It is not fruitful at all to harass all those wonderful developers that
bring us the best chess engine in the world, Stockfish. If you feel you are
smarter than them, create your own project, your very own chess engine.
Then we could return the favor and harass you back. I’m sure you’ll be
extremely delighted by this.

**Comment by PedanticHacker** [comment]
Please stop. You can’t have everything in life, especially not by brute
force. Also, you can’t force other people to do what you want to see or
have in their own creation. If you want anything in life, to be truly
yours, make it yourself. So, stop with this bullshit and make your own
chess engine. That way, you’ll have total and complete control over how
exactly will your very own chess engine behave. Thank you. I hope you find
peace soon.

**Comment by atumanian** [comment]
@LichessMaster
Sorry, I don't have much time to review these new cases. But these is enough evidence the owners of the Stockfish repo repress opinions they don't like.

@bftjoe
If you think other accounts are mine please provide proofs.

**Comment by atumanian** [comment]
@FishCooking @DeepBlue0 @LichessMaster
Are you the same person?

**Comment by Frosty54** [comment]
We are different persons. Joachim simply copy my repos.

**Comment by Joachim26** [comment]
> We are different persons. Joachim simply copy my repos.

😂

**Comment by Joachim26** [comment]
And DeepBlue blocked.

**Comment by atumanian** [comment]
@DeepBlue0
Glad to see you too. But I don't understand why you report such cases in this unrelated PR. You can write in my topic on Fishcooking or create a dedicated PR in Macro's repo.
There is already enough evidence there's no freedom of expressing opinions about Stockfish's development in the GitHub repo. No further actions needed to prove this.

**Comment by Frosty54** [comment]
Yes, I agree with you  atumanian. He block peoples and me also for no reason and without any arguments.

**Comment by Frosty54** [comment]
I don't familiar with Vondele. @Joachim26 sticks to everyone and just as ready to call you names or say that you are a troll. Maybe Joachim is Vondele under different account?

**Comment by Frosty54** [comment]
No one likes the truth and it's true.

**Comment by atumanian** [comment]
@DeepBlue0
> I don't know who are the other users

Ok, sorry for asking this.

@Frosty54
Yes, and very frustrating is the fact that only victims understand the situation isn't normal. Others only blame the victims instead of the true offenders.

**Comment by ghost** [comment]
@atumanian @mhouppin @Disservin 

The Only Two Pieces of Advice You'll Ever Need 

# First From Thomas Edison

image

# Second From Thomas Edison

image

**Comment by PedanticHacker** [comment]
Intrusive people can’t have everything in life, simply because the sheer
intrusiveness repels the experience of everything. That is the law of the
universe.

**Comment by Matthies** [comment]
https://www.youtube.com/watch?v=XkxtxZSrPMQ

**Comment by microsmeta** [comment]
...If Nikola Tesla would have played chess, it would also have been much
better than Edison on this game... 😊

Il giorno dom 9 apr 2023 alle ore 13:28 FishCooking <
***@***.***> ha scritto:

**Comment by Frosty54** [comment]
Stockfish 15.1 with one cpu in Droidfish says Qe4 at 30 depth.

**Comment by cj5716** [comment]
@BehindTheEyes 
I am not protonspring. Please do not confuse us

**Comment by atumanian** [comment]
@BehindTheEyes 
Thank you for your support! I really appreciate it.

**Comment by Matthies** [comment]
@BehindTheEyes ... just a vacuum in your case.

**Comment by Vechus** [comment]
@BehindTheEyes may I ask you why did you tag me in the comment? What do I have to do with this?

**Comment by Photoshop2023** [comment]
_To Aram Tumanian_ 

https://user-images.githubusercontent.com/130510640/231829579-dd5ef832-67ac-4364-aee3-096ca5193ab6.mp4

**In your eyes I see pain but your light gives me faith,
In your voice, is grief ,still your words have grace,
I know your heart is broken ,I know you are in pain
I know no word can comfort , Just know that we are here in prayer**

**Comment by Frosty54** [comment]
I already said that Stockfish 15.1 found Qe4 on depth 30 with default parameters. Why we are talking about that?

**Comment by KingdomOfNorthBarchant** [comment]
On March 22, 2023, the Kingdom of North Barchant hosted its inaugural online chess tournament at lichess.org. The tournament was a success, attracting many new users, and we plan to continue hosting regular tournaments in the future. To increase participation, we will pay for advertising and encourage people to register at lichess.

We would like to request permission to use our own flag, in addition to the pirate or any other flag. The Kingdom of North Barchant is a micronation, and our citizens would be proud to display the flag of their state during the tournament. We appreciate your consideration and thank you for your support.
229773693-fe9939be-3625-47c6-a9c5-98e722d3b756

229774075-cdd2fd55-8b76-4c0b-bc10-d340a54d7afa

**Comment by ghost** [comment]
@ZealanL @DaniSpringer @shadizahran @SomeOtherDev @atumanian @Vizvezdenec @PedanticHacker

**Comment by ZealanL** [comment]
> ![] @ZealanL @DaniSpringer @shadizahran @SomeOtherDev @atumanian @Vizvezdenec @PedanticHacker

What?

**Comment by ghost** [comment]
> I've blocked @atumanian in light of this discussion.
> 
> _Originally posted by @vondele in https://github.com/official-stockfish/Stockfish/issues/4195#issuecomment-1279968617_

Everyday I ask myself,
What will I have to do to be a man?
Do I have to stand and fight,
To prove to everybody who I am?
Is this what my life is for,
To waste in a world full of war?
Tell me why 
Does it have to be like this?
Tell me why 
Is there something I have missed?
Tell me why 
Cos I don't understand?
When so many need somebody,
We don't give a helping hand
@ZealanL Tell me why?

**Comment by Matthies** [comment]
I have sent a report to Github about stealing my identity and violating copyright of my logo. Stay tuned...

**Comment by ghost** [comment]
> I have sent a report to Github about stealing my identity and violating copyright of my logo. Stay tuned...

@Matthies You are owner of @RubiChess. Why you sent a report to Github for yourself ?!!! 😊😊😊

Untitled

Good Luck

**Comment by Matthies** [comment]
Thank you for the organization but I don't need it and so I deleted it.

**Comment by cj5716** [comment]
> > ![] @ZealanL @DaniSpringer @shadizahran @SomeOtherDev @atumanian @Vizvezdenec @PedanticHacker
> 
> What?

those are trolls randomly pinging people

**Comment by tissatussa** [comment]
nowadays the SF community seems to be a target for those trolls to get attention or to get some message out or just to connect subjects which are not related, etc. etc. .. i have no clue, it's ridiculous .. don't give them attention, at all.

**Pull request closed without merging**
