### PR TITLE
BSF Hardware Optimize for 64-bit

### PR DESCRIPTION
**Pull request by iGeek098**
intel64 & amd64 introduced new instructions BSF & BSR, using them is better

### CODE REVIEW

**Comment by iGeek098** [comment]
about 16.66666% better performance with new ins. the bench command
64** vs 55** ms

**Comment by iGeek098** [comment]
40/4 (40 move / 4 minutes) match results ongoing

**Comment by iGeek098** [comment]
11 & 12 matches
220816 is with this edit
170816 w/o it
about 10% ~ 15% better evaluated positions per seconds
2 matches 2 draw

in 11 2208 is the black
in 12 2208 is the white

https://drive.google.com/open?id=0B43TqiJrfv6OT2FJcTU3MDctbTA

**Comment by iGeek098** [comment]
then?

**Comment by mcostalba** [comment]
64 bit support is already included,  see bitboard. H

Anyhow your measure is wrong,  it can't be 15%.

You should speed test with bench command

**Comment by iGeek098** [comment]
okay but any machine runs bitboard::init() runs bsf_index() at start of the program (which doesnt use hardware)
and yeah my bench is wrong problem with the UI

BTW please i just have a question
while looking at the code i noticed that the used magic num. DeBruijn32 =0x78291ACF
while at https://chessprogramming.wikispaces.com/BitScan#MattTaylorsFoldingtrick
it say's :"There are only two magic 32-bit constants with the combined property of 32- and 64-bit De Bruijn sequences to apply this minimal perfect hashing:"

and they used 0x78291ACF so please out of all other billions of sequences how could you find this one, however it's a debruijn sequence so if you know how it works or a source i'd really appreciate it
thanks

**Comment by mcostalba** [comment]
I copied the value from chessprogramming wiki, I don't know how the
original author found that particular number.


On Tue, Aug 23, 2016 at 10:29 PM, Youssef Mohammed <notifications@github.com

**Comment by lantonov** [comment]
De Bruijn sequences can be constructed by one of several ways:

1.  Taking a Hamiltonian path of an n-dimensional De Bruijn graph over k symbols (or equivalently, a Eulerian cycle of a (n − 1)-dimensional De Bruijn graph) 
 Ref: Klein, Andreas (2013), Stream Ciphers , Springer, p. 59, ISBN 9781447150794.

2.  Concatenating together, in lexicographic order, all the Lyndon words whose length divides n.
 Ref: Berstel, Jean; Perrin, Dominique (2007), "The origins of combinatorics on words", European Journal of Combinatorics, 28 (3): 996–1022, doi:10.1016/j.ejc.2005.07.019

3. Via shift registers
 Ref:  Goresky, Mark; Klapper, Andrew (2012), "8.2.5 Shift register generation of de Bruijn sequences", Algebraic Shift Register Sequences , Cambridge University Press, pp. 174–175, ISBN 9781107014992.

4. Via finite fields
 Ref: Ralston, Anthony (1982), "de Bruijn sequences—a model example of the interaction of discrete mathematics and computer science", Mathematics Magazine, 55 (3): 131–143, doi:10.2307/2690079

**Comment by iGeek098** [comment]
well, at first i thank you for caring about that and answering
secondly i know this about debruijn sequences but actually these numbers aren't debruijn sequences (Because the same number appears twice in the sequence)

and depending onn wikispaces CPW these two numbers only works for this algo. however on google groups "within matt Taylor post" sb have said that there many but I don't understand if there are other none brute force way to find them (" I want to understand them mathematically")

and thank you again

**Comment by iGeek098** [comment]
about the original commit as I said this not optimized function is called at start of SF so change it please

**Comment by lantonov** [comment]
For a de Bruijn sequence with length 64, the non-repeating sequence is 6-bit (because k^n = 2^6 = 64). For length 32 the non-repeating sequence is 5-bit. This doesn't mean, however, that sequences in hexadecimals will not have repeating numbers. It is quite possible for those to have repeats. The 64-length sequence in Stockfish 3F79D71B4CB0A89 is binary 1111110111100111010111000110110100110010110000101010001001. You can easily see that there are no repeating overlapping 6-bit subsequences.

Another de Bruijn sequences of length 64 is, for example, ‭218A392CD3D5DBF‬, binary 1000011000101000111001001011001101001111010101110110111111, which also has hexadecimal repeats. Substituting it for the present one is unlikely to have any effect. Probably, it will be a non-functional change.

Otherwise, the number of possible de Bruijn sequences is (k!)^(k^(n-1)) / k^n. For k = 2 and n = 6, this makes 67108864 possible de Bruijn sequences.

**Comment by lantonov** [comment]
If you want to make these sequences cyclic, you add 5 bits at the end, like this (with 218A392CD3D5DBF‬):
1000011000101000111001001011001101001111010101110110111111|00000
to make a total of 69 bits.
These additional bits look like 2 loops in the de Bruijn graph (for the 2 sides of the linear sequence).

**Comment by iGeek098** [comment]
Thank you so much this helped me much sorry about all this delay

But I just meant the usage of debruijn sequence is when its multiplied with (00010000000 or 00000000100 or any binum contains only one (1) and then shifting right 32-5 will give the last five bits which gives identical values depending on the one (1) multiply number

How ever this sequence here is different as when it is multyplied by(0000000111111 or 0001111111111 format is containing zeros then containing ones) will give identical 5 bits

Also examining that sequence you will find two 5bits are the same and this can't happen in debruijn seq so they at wikispaces called it debruijn like seq however I found that it can be found by making finding path in n-diminesion Hamilton world(I can explain how to do this with more insights)

And this way is brute-force like so my question which is the best way to find these sequences (,I will use in another project that is all)

Thanks in advance

**Comment by iGeek098** [comment]
Forgot to mention in the debruijn like-sequence the 5bits is found twice when considered as debeuijn(multplied by 001000 format nuns same as shifting) however that doesn't happen when multiplying by 0001111111 format binary

**Comment by iGeek098** [comment]
If you looked at the first 6bits in that sequence they are 111111 so basically the first 5bits  |11111|1 the second 5bits 1|11111| wow they are repeated 11111 this is what I mean

**Comment by iGeek098** [comment]
Another crazy thing is these sequences use at matt Taylor folding trick giving 6 bits identical sequence on a 32bit magic number when multiplied with 0001111 type (zeros the ones) and 1110000(ones then zeros) type please help I need to use this in GO AI

**Comment by lantonov** [comment]
I cannot understand the reason for the multiplications (maybe I have to look in the applications you mentioned - Hamiltonian space, etc.). I would just like to note that for the 64 bit de Bruijn sequences it is entirely possible, even unavoidable, to have 5bit repeats, just as for 32bit sequences it is possible to have 4bit repeats.

**Comment by iGeek098** [comment]
What I mean can be found at wikispaces chessprograming I will mention the exacrt url here https://chessprogramming.wikispaces.com/BitScan#
Called mat Taylor folding trick and another 64 bit trick

The reason of using these debruijns is to know the fsb fast by sw so in some part they converted this 000000011111 (the point where ones started is fsb) so by addition by one its(0000010000) then multiply with debruijn seq will give you identical 5 bits number when used as precreatef array will give you where were fsb (first set(equal to 1) bit) mathematically true however some one his name on the bit scan skipped the addition step and used new kind of sequence but no academic theory about them, then matt Taylor found magic nums more werid and of course no theory these allowed to know fsb the shift in 64 (quad word) on 32 machines

I want somethimg other than brute force to find magics for 128 on 64 machine however his brute force way will try the whole process for the whole 2^128 combinations until valid is found, I'm trying to make a way by Hamilton's spaces that is it

**Comment by lantonov** [comment]
Thanks for the link. Bitscans seem to be quite a large field with which I am not well acquainted. Well, there is always something to learn.

**Pull request closed without merging**
