### PR TITLE
Tweak advanced_pawn_push()

### PR DESCRIPTION
**Pull request by alexdrag**
bench: 9087705

### CODE REVIEW

**Comment by mcostalba** [comment]
Where is the test result of this tweak?

**Comment by lantonov** [comment]
@mcostalba  I can test the revert if you don't mind, as this has already been committed

**Comment by lantonov** [comment]
@mcostalba Does it deserve testing? If yes, I can do it

**Comment by mcostalba** [comment]
Yes of course, you are free to test it.

**Pull request closed without merging**
